### ISSUE TITLE
automate poweroff/reboot functionality to html button

### ISSUE THREAD

**Issue by jaustinford** [jaustinford/ansible-es-labs#24]
Just want a series of either php buttons or something that you can click on and run the poweroff/reboot function in the background.

**Comment by drew-holt** [comment]
A couple thoughts;
* Create a script such that the html link would be https://myhost.com/my.php?k=MY_TOKEN&state=reboot (or shutdown)
* Add MY_TOKEN to your apache conf as a variable
Then php it out like;
```
<?php
$k = $_GET['k'];
$state = $_GET['state'];
$v =  getenv('MY_TOKEN');

if ($k === $v) {
  switch ($state) {
      case reboot:
          echo "i equals 0";
          break;
      case shutdown:
          echo "i equals 1";
          break;
  }
}
?>
```
Which ever user/group is running the httpd daemon would need escalated privileges to systemd 👎.

**Comment by jaustinford** [comment]
Oh cool I'll look into it. I was finding mostly ancient stackoverflow posts where they want to call a shell script which is what I'm gonna need since I had to write out a beefy [bootstrap](https://github.com/jaustinford/ansible-es-labs/blob/master/scripts/bootstrap-es.sh) script to shutdown the whole lab. So I was hoping something like:
```
<?php
shell_exec("/path/to/script.sh");
?>
```

**Comment by drew-holt** [comment]
Another approach might be that your php script writes to a temp file, if the content of the temp file are empty, reboot, or shutdown - then have a cron job run as root every minute to check the status and reboot/halt/do nothing. Just need to make sure the script cleans up after itself.
